version: '3'
services:
  portfolio:
    build: .
    image: portfolio:latest
    command: npm run preview -- --port 4321 --host 0.0.0.0  # Adicionando o parâmetro --host
    ports:
      - "8080:4321"
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - portfolio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
