version: "3.3"

services:
  portfolio:
    build: .
    container_name: portfolio
    restart: always
    ports:
      - "4322:4321"  # Alterando a porta externa para 4322
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portfolio
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
